/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tirupatibalajichitfund.ui;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import tirupatibalajichitfund.db.AllCommitteeClass;
import tirupatibalajichitfund.db.AllMemberClass;
import tirupatibalajichitfund.db.CommitteeData;
import tirupatibalajichitfund.db.MemberData;
import tirupatibalajichitfund.db.MemberInfoClass;
import tirupatibalajichitfund.db.MemberInfoData;
import tirupatibalajichitfund.utility.MemberInfoUtility;

/**
 *
 * @author abhishek
 */
public class AddMemberToCommittee extends javax.swing.JFrame {
    
    private MemberData selectedMember;
    private CommitteeData selectedCommittee;
    private int totalenteries;

    /**
     * Creates new form AddMember
     */
    public AddMemberToCommittee() {
        initComponents();
        committeeList.setEnabled(false);
        enteriesCombo.setEnabled(false);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setupMemberCombo();
    }
    
    private void setupMemberCombo() {
        try {
            memberList.addItem("None");
            ArrayList<MemberData> allmemberlist = AllMemberClass.getInstance().getAllMembersActive();
            for (MemberData data : allmemberlist) {
                memberList.addItem(data.getUid() + " " + data.getName());
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMemberToCommittee.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        memberList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enteriesCombo = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        committeeList = new javax.swing.JComboBox();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        titleLabel.setText("ADD MEMBER TO COMMITTEE");

        memberList.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        memberList.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        memberList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberListActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setText("SELECT MEMBER:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel2.setText("SELECT ENTERIES:");

        enteriesCombo.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        enteriesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        enteriesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enteriesComboActionPerformed(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("SELECT COMMITTEE:");

        committeeList.setFont(new java.awt.Font("Ubuntu", 1, 16)); // NOI18N
        committeeList.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        committeeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                committeeListActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        resetButton.setText("RESET");
        resetButton.setPreferredSize(new java.awt.Dimension(84, 33));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(enteriesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(292, 292, 292))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(memberList, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(committeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberList, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(committeeList, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enteriesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void setupCommitteeCombo() {
        committeeList.addItem("None");
        try {
            ArrayList<CommitteeData> allcommitteelist = AllCommitteeClass.getInstance().getAllCommitteesActive();
            for (CommitteeData data : allcommitteelist) {
                committeeList.addItem(data.getCfid() + " " + data.getCname());
            }
        } catch (Exception ex) {
            Logger.getLogger(AddMemberToCommittee.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void setupEnteries() {
        enteriesCombo.addItem("None");
        for (int i = 1; i < 5; i++) {
            enteriesCombo.addItem(i + "");
        }
    }
    private void memberListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberListActionPerformed
        // TODO add your handling code here:
        if (memberList.equals(evt.getSource())) {
            String selMem = (String) memberList.getSelectedItem();
            if (selMem.equals("None")) {
                enteriesCombo.setEnabled(false);
                committeeList.setEnabled(false);
                addButton.setEnabled(false);
                return;
            }
            try {
                MemberData mem = AllMemberClass.getInstance().getMember(Integer.parseInt(selMem.substring(0, 4)));
                //JOptionPane.showMessageDialog(this,"Mem-"+mem.getPhone());
                // enteriesCombo.setEnabled(true);
                this.selectedMember = mem;
                committeeList.setEnabled(true);
                setupCommitteeCombo();
            } catch (Exception ex) {
                Logger.getLogger(AddMemberToCommittee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_memberListActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void committeeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_committeeListActionPerformed
        // TODO add your handling code here:
        if (committeeList.equals(evt.getSource())) {
            String selCom = (String) committeeList.getSelectedItem();
            if (selCom.equals("None")) {
                enteriesCombo.setEnabled(false);
                addButton.setEnabled(false);
                return;
            }
            try {
                CommitteeData com = AllCommitteeClass.getInstance().getCommittee(Integer.parseInt(selCom.substring(0, 6)));
                JOptionPane.showMessageDialog(this, "Com-" + com.getCname());
                this.selectedCommittee = com;
                enteriesCombo.setEnabled(true);
                setupEnteries();
            } catch (Exception ex) {
                Logger.getLogger(AddMemberToCommittee.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_committeeListActionPerformed

    private void enteriesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enteriesComboActionPerformed
        // TODO add your handling code here:
        if (enteriesCombo.equals(evt.getSource())) {
            String enteries = (String) enteriesCombo.getSelectedItem();
            if (enteries.equals("None")) {
                addButton.setEnabled(false);
                return;
            }
            int entry = Integer.parseInt(enteries);
            if (this.selectedCommittee != null) {
                int totalentry = MemberInfoClass.getInstance().getEnteriesSumForCfid(this.selectedCommittee.getCfid());
                if (totalentry == -1) {
                    JOptionPane.showMessageDialog(this, "Some error occurred while fetching total members");
                    return;
                }
                if ((totalentry + entry) > 19) {
                    JOptionPane.showMessageDialog(this, "Total Members in Committee " + (totalentry + entry) + " exceeds 19");
                    return;
                }
                
            }
            this.totalenteries = entry;
            addButton.setEnabled(true);
        }
    }//GEN-LAST:event_enteriesComboActionPerformed
    
    private void reset() {
        committeeList.setSelectedIndex(0);
        enteriesCombo.setSelectedIndex(0);
        memberList.setSelectedIndex(0);
    }
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        if (addButton.equals(evt.getSource())) {
            if (selectedMember != null && selectedCommittee != null) {
                String refkey = MemberInfoUtility.getInstance().formRefKey(selectedMember, selectedCommittee, totalenteries);
                if (refkey == null) {
                    JOptionPane.showMessageDialog(this, "Unable to perform operation");
                    return;
                }
                ArrayList<MemberInfoData> meminfdat = MemberInfoClass.getInstance().getDatasetForCfid(selectedCommittee.getCfid());
                for (MemberInfoData mid : meminfdat) {
                    if (mid.getMember().getName().equals(selectedMember.getKName())) {
                        JOptionPane.showMessageDialog(this, "Member already in present committee");
                        return;
                    }
                }
                int ans = JOptionPane.showConfirmDialog(this, "Are you sure you want to add " + selectedMember.getName()
                        + " to committee " + selectedCommittee.getCname() + " with entries " + totalenteries);
                if (ans == JOptionPane.YES_OPTION) {
                    MemberInfoUtility.getInstance().addNewEntry(selectedMember, selectedCommittee, totalenteries, refkey);
                    reset();
                }
            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        if (resetButton.equals(evt.getSource())) {
            reset();
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMemberToCommittee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMemberToCommittee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMemberToCommittee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMemberToCommittee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMemberToCommittee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox committeeList;
    private javax.swing.JComboBox enteriesCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox memberList;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
